# Site Info
title: All This
tagline: 'Programming, Machine Learning & NLP'
description: ''
baseurl: ""
url: http://psuryan.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-mermaid
  - jekyll-gist

markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact 
author:
  name: psuryan
  description:
  gravatar: 485a2815144d1865395b34f6f0e0970a
  contact:
    linkedin:  https://www.linkedin.com/in/psuryan
    github: https://github.com/psuryan
    stack-overflow: https://stackoverflow.com/story/psuryan
    orcid: https://orcid.org/0000-0002-8619-2976
    # facebook:  <hide>
    # twitter:   
    # weibo:     
    # email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  #Github Project: 
  #  - 'http://psuryan.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
mermaid: 
  src: 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.1.2/mermaid.js'
google_analytics_token: UA-131755574-1
disqus_short_name: # leave blank if you don't want disqus

